### ISSUE TITLE
built-in modules

### ISSUE THREAD

**Issue by ScolderCreations** [MystPi/talon#1]
might allow things like sys.platform to be used in Talon

**Comment by MystPi** [comment]
Talon already has some [builtins](https://github.com/MystPi/talon/blob/main/talon/environment.py), but namespaces are a good idea. It would take some extra work, but I might look into it eventually.

**Comment by ScolderCreations** [comment]
There’s a difference from builtin commands than builtin modules.

**Comment by MystPi** [comment]
> There’s a difference from builtin commands than builtin modules.

I know, but Talon doesn't have support for modules yet.
